name: Build QUANTIX AI CORE (APK, EXE, Web)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - debug

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    - name: Flutter Dependencies
      run: flutter pub get
    - name: Crear archivo .env para la build
      run: |
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env
    - name: Build APK (Release)
      if: github.event.inputs.build_type != 'debug'
      run: flutter build apk --release --target-platform android-arm64
    - name: Build APK (Debug)
      if: github.event.inputs.build_type == 'debug'
      run: flutter build apk --debug --target-platform android-arm64
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: quantix-ai-core-android-apk
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 30

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    - name: Enable Windows Desktop
      run: flutter config --enable-windows-desktop
    - name: Flutter Dependencies
      run: flutter pub get
    - name: Crear archivo .env para la build de Windows
      run: echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env
    - name: Build Windows (Release)
      if: github.event.inputs.build_type != 'debug'
      run: flutter build windows --release
    - name: Build Windows (Debug)
      if: github.event.inputs.build_type == 'debug'
      run: flutter build windows --debug
    - name: Create Windows ZIP
      run: |
        cd build/windows/x64/runner
        if ('${{ github.event.inputs.build_type }}' -eq 'debug') {
          Compress-Archive -Path Debug/* -DestinationPath quantix-ai-core-windows-debug.zip
        } else {
          Compress-Archive -Path Release/* -DestinationPath quantix-ai-core-windows-release.zip
        }
    - name: Upload Windows EXE
      uses: actions/upload-artifact@v4
      with:
        name: quantix-ai-core-windows-exe
        path: build/windows/x64/runner/*.zip
        retention-days: 30

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
    - name: Flutter Dependencies
      run: flutter pub get
    - name: Crear archivo .env para la build web
      run: echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" > .env
    - name: Build Web (Release)
      run: flutter build web --release
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: quantix-ai-core-web
        path: build/web
        retention-days: 30 